name: woue_components_fluent
description: A new Flutter package project.
version: 0.0.1


environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  woue_components:
      git:
       url: https://github.com/cracklye/woue_components.git
    #path: ../../woue_components
  fluent_ui:
  
  desktop_drop:
  loggy:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
